<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ZucchiUploader\Module'                     => __DIR__ . '//Module.php',
    'ZucchiUploader\Controller\Plugin\Uploader' => __DIR__ . '//src/ZucchiUploader/Controller/Plugin/Uploader.php',
    'ZucchiUploader\Options\UploaderOptions'    => __DIR__ . '//src/ZucchiUploader/Options/UploaderOptions.php',
    'ZucchiUploader\View\Helper\Uploader'       => __DIR__ . '//src/ZucchiUploader/View/Helper/Uploader.php',
    'ZucchiUploader\View\Helper\UploadQueue'    => __DIR__ . '//src/ZucchiUploader/View/Helper/UploadQueue.php',
);